//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.20

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "books")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub title: String,
    pub subtitle: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub language: String,
    pub publisher: String,
    pub isbn: String,
    pub page_count: i32,
    pub cover_path: String,
    pub published_date: Date,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    #[sea_orm(column_type = "Text")]
    pub sort_title: String,
    pub book_path: String,
    pub file_hash: String,
    pub size_bytes: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::authors_books::Entity")]
    AuthorsBooks,
    #[sea_orm(has_many = "super::book_files::Entity")]
    BookFiles,
    #[sea_orm(has_many = "super::identifiers::Entity")]
    Identifiers,
    #[sea_orm(has_many = "super::series_books::Entity")]
    SeriesBooks,
}

impl Related<super::authors_books::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuthorsBooks.def()
    }
}

impl Related<super::book_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BookFiles.def()
    }
}

impl Related<super::identifiers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Identifiers.def()
    }
}

impl Related<super::series_books::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SeriesBooks.def()
    }
}

impl Related<super::authors::Entity> for Entity {
    fn to() -> RelationDef {
        super::authors_books::Relation::Authors.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::authors_books::Relation::Books.def().rev())
    }
}

impl Related<super::series::Entity> for Entity {
    fn to() -> RelationDef {
        super::series_books::Relation::Series.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::series_books::Relation::Books.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
