//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "series")]
#[schema(as = Series)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub name: String,
    #[sea_orm(column_type = "Text")]
    pub description: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::series_books::Entity")]
    SeriesBooks,
}

impl Related<super::series_books::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SeriesBooks.def()
    }
}

impl Related<super::books::Entity> for Entity {
    fn to() -> RelationDef {
        super::series_books::Relation::Books.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::series_books::Relation::Series.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
