//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "authors")]
#[schema(as = Author)]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub sort_name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::authors_books::Entity")]
    AuthorsBooks,
}

impl Related<super::authors_books::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AuthorsBooks.def()
    }
}

impl Related<super::books::Entity> for Entity {
    fn to() -> RelationDef {
        super::authors_books::Relation::Books.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::authors_books::Relation::Authors.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
