//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::authors::Entity as Authors;
pub use super::authors_books::Entity as AuthorsBooks;
pub use super::books::Entity as Books;
pub use super::identifiers::Entity as Identifiers;
pub use super::series::Entity as Series;
pub use super::series_books::Entity as SeriesBooks;
